theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "sound"
driver = "auto"
step_width = 5

[[block]]
block = "net"
device = "wlp4s0"
ssid = true
signal_strength = true
speed_up = false
interval = 3
use_bits = false

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%d/%m %R"

